//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerApp.Properties.Lang {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerApp.Properties.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address:.
        /// </summary>
        public static string AddressPc {
            get {
                return ResourceManager.GetString("AddressPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на At the moment, there is no data to output statistics..
        /// </summary>
        public static string BorderSettings {
            get {
                return ResourceManager.GetString("BorderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Broadcast.
        /// </summary>
        public static string BroadcastButton {
            get {
                return ResourceManager.GetString("BroadcastButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorize.
        /// </summary>
        public static string ButtonAuth {
            get {
                return ResourceManager.GetString("ButtonAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        public static string ButtonSaveChanges {
            get {
                return ResourceManager.GetString("ButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show password.
        /// </summary>
        public static string CheckBoxAuth {
            get {
                return ResourceManager.GetString("CheckBoxAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close the program.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computers.
        /// </summary>
        public static string ComputerManagement {
            get {
                return ResourceManager.GetString("ComputerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Computer management.
        /// </summary>
        public static string ComputerManagementTitle {
            get {
                return ResourceManager.GetString("ComputerManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating a new user.
        /// </summary>
        public static string CreateUserTitle {
            get {
                return ResourceManager.GetString("CreateUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string ExitUdp {
            get {
                return ResourceManager.GetString("ExitUdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full description.
        /// </summary>
        public static string FullDescTitle {
            get {
                return ResourceManager.GetString("FullDescTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        public static string InfoButton {
            get {
                return ResourceManager.GetString("InfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Input name:.
        /// </summary>
        public static string InputNameApp {
            get {
                return ResourceManager.GetString("InputNameApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of teachers.
        /// </summary>
        public static string ListTeachTitle {
            get {
                return ResourceManager.GetString("ListTeachTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login:.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MainWindow:.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на mode.
        /// </summary>
        public static string ModeTitle {
            get {
                return ResourceManager.GetString("ModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        public static string NamePc {
            get {
                return ResourceManager.GetString("NamePc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PC Name:.
        /// </summary>
        public static string PcName {
            get {
                return ResourceManager.GetString("PcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ban.
        /// </summary>
        public static string StatBoxNo {
            get {
                return ResourceManager.GetString("StatBoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow.
        /// </summary>
        public static string StatBoxYes {
            get {
                return ResourceManager.GetString("StatBoxYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        public static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status:.
        /// </summary>
        public static string StatusPc {
            get {
                return ResourceManager.GetString("StatusPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FIO:.
        /// </summary>
        public static string TextBlockFIO {
            get {
                return ResourceManager.GetString("TextBlockFIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FirstName:.
        /// </summary>
        public static string TextBlockFirstName {
            get {
                return ResourceManager.GetString("TextBlockFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LastName:.
        /// </summary>
        public static string TextBlockLastName {
            get {
                return ResourceManager.GetString("TextBlockLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of specialties:.
        /// </summary>
        public static string TextBlockListSpec {
            get {
                return ResourceManager.GetString("TextBlockListSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input login:.
        /// </summary>
        public static string TextBlockLogin {
            get {
                return ResourceManager.GetString("TextBlockLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Network settings:.
        /// </summary>
        public static string TextBlockNetwork {
            get {
                return ResourceManager.GetString("TextBlockNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Office:.
        /// </summary>
        public static string TextBlockOffice {
            get {
                return ResourceManager.GetString("TextBlockOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input password:.
        /// </summary>
        public static string TextBlockPassword {
            get {
                return ResourceManager.GetString("TextBlockPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        public static string TextBlockPort {
            get {
                return ResourceManager.GetString("TextBlockPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Role:.
        /// </summary>
        public static string TextBlockRole {
            get {
                return ResourceManager.GetString("TextBlockRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SecondName:.
        /// </summary>
        public static string TextBlockSecondName {
            get {
                return ResourceManager.GetString("TextBlockSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a language:.
        /// </summary>
        public static string TextBlockSelectLang {
            get {
                return ResourceManager.GetString("TextBlockSelectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select specialization:.
        /// </summary>
        public static string TextBlockSelectSpec {
            get {
                return ResourceManager.GetString("TextBlockSelectSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a theme:.
        /// </summary>
        public static string TextBlockSelectTheme {
            get {
                return ResourceManager.GetString("TextBlockSelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string TitleAuth {
            get {
                return ResourceManager.GetString("TitleAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of allowed applications.
        /// </summary>
        public static string ToolTipListAppButton {
            get {
                return ResourceManager.GetString("ToolTipListAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information about your computer.
        /// </summary>
        public static string ToolTipPcInfoButton {
            get {
                return ResourceManager.GetString("ToolTipPcInfoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TurnOff.
        /// </summary>
        public static string TurnOffButton {
            get {
                return ResourceManager.GetString("TurnOffButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wait....
        /// </summary>
        public static string WaitingBlock {
            get {
                return ResourceManager.GetString("WaitingBlock", resourceCulture);
            }
        }
    }
}
